package main

import (
	"os"
	"testing"
)

// validateEnvKeys are the variables LoadStaticConfig/LoadDynamicConfig/
// LoadAbuseConfig read. Clearing just these keeps the ambient environment
// (PATH, HOME) intact while letting godotenv.Load populate each key from
// the fixture, and stays safe if tests ever run in parallel.
var validateEnvKeys = []string{
	"INSTANCE_ID", "ONION_HOSTS", "NO_CONTENT_LOGS", "LOG_FILE_PATH",
	"HISTORY_FILE_PATH", "TRUSTED_PROXY_DIR", "REQUIRE_TLS", "PORT",
	"TIMEZONE", "MAX_LOG_SIZE_MB", "MAX_HISTORY_FILE_SIZE_MB", "WEB_ENABLED",
	"ONION_ALLOW_WEB", "ONION_ALLOW_PASSKEY", "PROXY_PROVIDER", "STATUS_URL",
	"DOWNLOAD_URL", "HOMEPAGE_URL", "MAX_CONNECTIONS_PER_IP",
	"MAX_MESSAGE_LENGTH", "MAX_MESSAGE_LINE", "MESSAGE_COOLDOWN",
	"IDLE_CHAT_TIMEOUT", "MAX_HISTORY_BYTES", "MAX_HISTORY_SEND",
	"HISTORY_SEGMENT_COOLDOWN", "HISTORY_DISK_LOOKUP", "MAX_USERNAME_LENGTH",
	"MAX_TRIPCODE_LENGTH", "CONNECTION_COOLDOWN", "ALLOWED_ORIGINS",
	"DATA_DIR", "BEHAVIOR_ENABLED", "BEHAVIOR_GEOIP_DIR", "BEHAVIOR_FILE_PATH",
	"REQUIRE_IPV4", "BLOCKLIST_FILE",
	"MAX_TOTAL_CONNECTIONS", "ATTACK_ENTER_SECS", "ATTACK_ENTER_RPS",
	"UNDER_ATTACK_TTL", "UNDER_ATTACK_FORCE", "POW_FIRST_CONNECT",
	"POW_GATE_TIER", "POW_TIER_COUNT",
	"POW_P1_T", "POW_P1_M", "POW_P1_P", "POW_P1_DIFF", "POW_P1_EST_MS",
	"POW_P2_T", "POW_P2_M", "POW_P2_P", "POW_P2_DIFF", "POW_P2_EST_MS",
	"POW_P3_T", "POW_P3_M", "POW_P3_P", "POW_P3_DIFF", "POW_P3_EST_MS",
	"POW_TTL", "JOIN_WAIT_MIN", "JOIN_WAIT_MAX", "SCREEN_DEADLINE",
	"GATE_HTTP_ENABLED", "GATE_HTTP_CLASSES", "GATE_HTTP_MODE",
	"GATE_HTTP_TIER_MIN",
	"PASS_TTL", "PASS_SINGLE_USE",
	"BEHAVIOR_CURVE_GAMMA", "BEHAVIOR_WINDOW_SHORT", "BEHAVIOR_WINDOW_LONG",
	"BEHAVIOR_GAP_WINDOW", "BEHAVIOR_NIGHT_START", "BEHAVIOR_NIGHT_END",
	"BEHAVIOR_IDENTITY_GUEST", "BEHAVIOR_IDENTITY_TRIP", "BEHAVIOR_IDENTITY_KEY",
	"BEHAVIOR_W_RHYTHM", "BEHAVIOR_NMIN_RHYTHM", "BEHAVIOR_RAMP_RHYTHM_LO", "BEHAVIOR_RAMP_RHYTHM_HI",
	"BEHAVIOR_W_THROUGHPUT", "BEHAVIOR_NMIN_THROUGHPUT", "BEHAVIOR_RAMP_THROUGHPUT_LO", "BEHAVIOR_RAMP_THROUGHPUT_HI",
	"BEHAVIOR_W_NIGHT", "BEHAVIOR_NMIN_NIGHT", "BEHAVIOR_RAMP_NIGHT_LO", "BEHAVIOR_RAMP_NIGHT_HI",
	"BEHAVIOR_W_CONTINUITY", "BEHAVIOR_NMIN_CONTINUITY", "BEHAVIOR_RAMP_CONTINUITY_LO", "BEHAVIOR_RAMP_CONTINUITY_HI",
	"BEHAVIOR_W_CHURN", "BEHAVIOR_NMIN_CHURN", "BEHAVIOR_RAMP_CHURN_LO", "BEHAVIOR_RAMP_CHURN_HI",
	"BEHAVIOR_W_IDENTITY", "BEHAVIOR_NMIN_IDENTITY", "BEHAVIOR_RAMP_IDENTITY_LO", "BEHAVIOR_RAMP_IDENTITY_HI",
	"BEHAVIOR_W_IPREP", "BEHAVIOR_NMIN_IPREP", "BEHAVIOR_RAMP_IPREP_LO", "BEHAVIOR_RAMP_IPREP_HI",
	"BEHAVIOR_W_PROTOERR", "BEHAVIOR_NMIN_PROTOERR", "BEHAVIOR_RAMP_PROTOERR_LO", "BEHAVIOR_RAMP_PROTOERR_HI",
	"BEHAVIOR_W_HTTP_RATE", "BEHAVIOR_NMIN_HTTP_RATE", "BEHAVIOR_RAMP_HTTP_RATE_LO", "BEHAVIOR_RAMP_HTTP_RATE_HI",
	"BEHAVIOR_W_HTTP_ERROR", "BEHAVIOR_NMIN_HTTP_ERROR", "BEHAVIOR_RAMP_HTTP_ERROR_LO", "BEHAVIOR_RAMP_HTTP_ERROR_HI",
	"BEHAVIOR_W_ENDPOINT_FOCUS", "BEHAVIOR_NMIN_ENDPOINT_FOCUS", "BEHAVIOR_RAMP_ENDPOINT_FOCUS_LO", "BEHAVIOR_RAMP_ENDPOINT_FOCUS_HI",
	"BEHAVIOR_W_AUTH_PROBE", "BEHAVIOR_NMIN_AUTH_PROBE", "BEHAVIOR_RAMP_AUTH_PROBE_LO", "BEHAVIOR_RAMP_AUTH_PROBE_HI",
	"BEHAVIOR_W_ENVELOPE", "BEHAVIOR_NMIN_ENVELOPE", "BEHAVIOR_RAMP_ENVELOPE_LO", "BEHAVIOR_RAMP_ENVELOPE_HI",
	"BEHAVIOR_GROUP_BETA_IP", "BEHAVIOR_GROUP_BETA_48", "BEHAVIOR_GROUP_BETA_ASN",
	"BEHAVIOR_GROUP_BETA_COUNTRY", "BEHAVIOR_GROUP_MIN_MEMBERS",
	"BEHAVIOR_TIER1_ENTER", "BEHAVIOR_TIER1_EXIT",
	"BEHAVIOR_TIER2_ENTER", "BEHAVIOR_TIER2_EXIT",
	"BEHAVIOR_TIER3_ENTER", "BEHAVIOR_TIER3_EXIT",
	"POW_RECHECK_MIN", "POW_RECHECK_MAX",
	"ATTACK_SCALE_MODE", "ATTACK_SCALE_W_REJECT", "ATTACK_SCALE_W_CONNRATE",
	"ATTACK_SCALE_W_IPGROWTH", "ATTACK_SCALE_W_BLOCKLIST", "ATTACK_TIER_BUMP_MAX",
	"BEHAVIOR_RETENTION_P0", "BEHAVIOR_RETENTION_P1",
	"BEHAVIOR_RETENTION_P2", "BEHAVIOR_RETENTION_P3",
	"BEHAVIOR_STATS_ENABLED", "BEHAVIOR_STATS_WINDOW",
}

// withCleanEnv unsets the configuration variables for one test and
// restores them afterwards, so godotenv.Load can populate every key from
// the fixture .env without ambient values shadowing it.
func withCleanEnv(t *testing.T) {
	t.Helper()
	old := map[string]string{}
	present := map[string]bool{}
	for _, k := range validateEnvKeys {
		if v, ok := os.LookupEnv(k); ok {
			old[k] = v
			present[k] = true
		}
		_ = os.Unsetenv(k)
	}
	t.Cleanup(func() {
		for _, k := range validateEnvKeys {
			if present[k] {
				_ = os.Setenv(k, old[k])
			} else {
				_ = os.Unsetenv(k)
			}
		}
	})
}

const validValidateEnv = "PORT=10000\n" +
	"PROXY_PROVIDER=none\n" +
	"MAX_LOG_SIZE_MB=50\n" +
	"MAX_HISTORY_FILE_SIZE_MB=50\n" +
	"MAX_CONNECTIONS_PER_IP=2\n" +
	"MAX_MESSAGE_LENGTH=5000\n" +
	"MAX_MESSAGE_LINE=50\n" +
	"MESSAGE_COOLDOWN=200ms\n" +
	"IDLE_CHAT_TIMEOUT=30m\n" +
	"MAX_HISTORY_BYTES=10485760\n" +
	"MAX_HISTORY_SEND=500\n" +
	"HISTORY_SEGMENT_COOLDOWN=2s\n" +
	"HISTORY_DISK_LOOKUP=0\n" +
	"MAX_USERNAME_LENGTH=12\n" +
	"CONNECTION_COOLDOWN=5s\n" +
	"BEHAVIOR_ENABLED=true\n" +
	"BEHAVIOR_GEOIP_DIR=./config/geoip\n" +
	"BEHAVIOR_FILE_PATH=./data/behavior.jsonl\n" +
	"REQUIRE_IPV4=false\n" +
	"BLOCKLIST_FILE=./config/blocklist.txt\n" +
	"MAX_TOTAL_CONNECTIONS=500\n" +
	"ATTACK_ENTER_SECS=5s\n" +
	"ATTACK_ENTER_RPS=50\n" +
	"UNDER_ATTACK_TTL=10m\n" +
	"UNDER_ATTACK_FORCE=auto\n" +
	"POW_FIRST_CONNECT=under-attack\n" +
	"POW_GATE_TIER=1\n" +
	"POW_TIER_COUNT=4\n" +
	"POW_P1_T=1\nPOW_P1_M=8192\nPOW_P1_P=1\nPOW_P1_DIFF=16\nPOW_P1_EST_MS=500\n" +
	"POW_P2_T=1\nPOW_P2_M=16384\nPOW_P2_P=1\nPOW_P2_DIFF=20\nPOW_P2_EST_MS=2000\n" +
	"POW_P3_T=1\nPOW_P3_M=32768\nPOW_P3_P=1\nPOW_P3_DIFF=24\nPOW_P3_EST_MS=8000\n" +
	"POW_TTL=2m\n" +
	"JOIN_WAIT_MIN=30s\n" +
	"JOIN_WAIT_MAX=60s\n" +
	"SCREEN_DEADLINE=5m\n" +
	"GATE_HTTP_ENABLED=true\n" +
	"GATE_HTTP_CLASSES=trip_verify,webauthn_finish\n" +
	"GATE_HTTP_MODE=under-attack\n" +
	"GATE_HTTP_TIER_MIN=1\n" +
	"PASS_TTL=10m\n" +
	"PASS_SINGLE_USE=false\n" +
	"BEHAVIOR_CURVE_GAMMA=2\n" +
	"BEHAVIOR_WINDOW_SHORT=10m\n" +
	"BEHAVIOR_WINDOW_LONG=1h\n" +
	"BEHAVIOR_GAP_WINDOW=30m\n" +
	"BEHAVIOR_NIGHT_START=2\n" +
	"BEHAVIOR_NIGHT_END=5\n" +
	"BEHAVIOR_IDENTITY_GUEST=1\n" +
	"BEHAVIOR_IDENTITY_TRIP=0.4\n" +
	"BEHAVIOR_IDENTITY_KEY=0.15\n" +
	"BEHAVIOR_W_RHYTHM=0.18\nBEHAVIOR_NMIN_RHYTHM=20\nBEHAVIOR_RAMP_RHYTHM_LO=0.1\nBEHAVIOR_RAMP_RHYTHM_HI=0.8\n" +
	"BEHAVIOR_W_THROUGHPUT=0.15\nBEHAVIOR_NMIN_THROUGHPUT=10\nBEHAVIOR_RAMP_THROUGHPUT_LO=20\nBEHAVIOR_RAMP_THROUGHPUT_HI=300\n" +
	"BEHAVIOR_W_NIGHT=0.12\nBEHAVIOR_NMIN_NIGHT=30\nBEHAVIOR_RAMP_NIGHT_LO=0.05\nBEHAVIOR_RAMP_NIGHT_HI=0.6\n" +
	"BEHAVIOR_W_CONTINUITY=0.12\nBEHAVIOR_NMIN_CONTINUITY=10\nBEHAVIOR_RAMP_CONTINUITY_LO=4\nBEHAVIOR_RAMP_CONTINUITY_HI=16\n" +
	"BEHAVIOR_W_CHURN=0.10\nBEHAVIOR_NMIN_CHURN=5\nBEHAVIOR_RAMP_CHURN_LO=3\nBEHAVIOR_RAMP_CHURN_HI=30\n" +
	"BEHAVIOR_W_IDENTITY=0.10\nBEHAVIOR_NMIN_IDENTITY=1\nBEHAVIOR_RAMP_IDENTITY_LO=0\nBEHAVIOR_RAMP_IDENTITY_HI=1\n" +
	"BEHAVIOR_W_IPREP=0.15\nBEHAVIOR_NMIN_IPREP=5\nBEHAVIOR_RAMP_IPREP_LO=5\nBEHAVIOR_RAMP_IPREP_HI=50\n" +
	"BEHAVIOR_W_PROTOERR=0.08\nBEHAVIOR_NMIN_PROTOERR=1\nBEHAVIOR_RAMP_PROTOERR_LO=0\nBEHAVIOR_RAMP_PROTOERR_HI=5\n" +
	"BEHAVIOR_W_HTTP_RATE=0.10\nBEHAVIOR_NMIN_HTTP_RATE=5\nBEHAVIOR_RAMP_HTTP_RATE_LO=1\nBEHAVIOR_RAMP_HTTP_RATE_HI=30\n" +
	"BEHAVIOR_W_HTTP_ERROR=0.10\nBEHAVIOR_NMIN_HTTP_ERROR=5\nBEHAVIOR_RAMP_HTTP_ERROR_LO=0\nBEHAVIOR_RAMP_HTTP_ERROR_HI=1\n" +
	"BEHAVIOR_W_ENDPOINT_FOCUS=0.10\nBEHAVIOR_NMIN_ENDPOINT_FOCUS=5\nBEHAVIOR_RAMP_ENDPOINT_FOCUS_LO=0\nBEHAVIOR_RAMP_ENDPOINT_FOCUS_HI=1\n" +
	"BEHAVIOR_W_AUTH_PROBE=0.10\nBEHAVIOR_NMIN_AUTH_PROBE=1\nBEHAVIOR_RAMP_AUTH_PROBE_LO=0\nBEHAVIOR_RAMP_AUTH_PROBE_HI=5\n" +
	"BEHAVIOR_W_ENVELOPE=0.10\nBEHAVIOR_NMIN_ENVELOPE=1\nBEHAVIOR_RAMP_ENVELOPE_LO=0\nBEHAVIOR_RAMP_ENVELOPE_HI=5\n" +
	"BEHAVIOR_GROUP_BETA_IP=0.6\n" +
	"BEHAVIOR_GROUP_BETA_48=0.5\n" +
	"BEHAVIOR_GROUP_BETA_ASN=0.3\n" +
	"BEHAVIOR_GROUP_BETA_COUNTRY=0.2\n" +
	"BEHAVIOR_GROUP_MIN_MEMBERS=2\n" +
	"BEHAVIOR_TIER1_ENTER=0.25\nBEHAVIOR_TIER1_EXIT=0.18\n" +
	"BEHAVIOR_TIER2_ENTER=0.55\nBEHAVIOR_TIER2_EXIT=0.45\n" +
	"BEHAVIOR_TIER3_ENTER=0.8\nBEHAVIOR_TIER3_EXIT=0.7\n" +
	"POW_RECHECK_MIN=5m\n" +
	"POW_RECHECK_MAX=15m\n" +
	"ATTACK_SCALE_MODE=max\n" +
	"ATTACK_SCALE_W_REJECT=1\n" +
	"ATTACK_SCALE_W_CONNRATE=1\n" +
	"ATTACK_SCALE_W_IPGROWTH=1\n" +
	"ATTACK_SCALE_W_BLOCKLIST=1\n" +
	"ATTACK_TIER_BUMP_MAX=1\n" +
	"BEHAVIOR_RETENTION_P0=24h\n" +
	"BEHAVIOR_RETENTION_P1=72h\n" +
	"BEHAVIOR_RETENTION_P2=168h\n" +
	"BEHAVIOR_RETENTION_P3=720h\n" +
	"BEHAVIOR_STATS_ENABLED=true\n" +
	"BEHAVIOR_STATS_WINDOW=15m\n"

func TestConfigValidatePass(t *testing.T) {
	withCleanEnv(t)
	root := t.TempDir()
	writeTree(t, root, map[string]string{
		".env":              validValidateEnv,
		"config/roles.json": "{}\n",
	})
	cmd := &ConfigValidateCmd{To: root, Format: "json"}
	if err := cmd.Run(); err != nil {
		t.Fatalf("valid instance must pass: %v", err)
	}
}

func TestConfigValidateFailsOnProxyProvider(t *testing.T) {
	withCleanEnv(t)
	root := t.TempDir()
	writeTree(t, root, map[string]string{
		".env": "PORT=10000\nPROXY_PROVIDER=false\n" +
			"MAX_LOG_SIZE_MB=50\nMAX_HISTORY_FILE_SIZE_MB=50\n",
		"config/roles.json": "{}\n",
	})
	cmd := &ConfigValidateCmd{To: root, Format: "json"}
	if err := cmd.Run(); err == nil {
		t.Fatal("PROXY_PROVIDER=false must fail validate")
	}
}

func TestConfigValidateFailsOnBadRoles(t *testing.T) {
	withCleanEnv(t)
	root := t.TempDir()
	writeTree(t, root, map[string]string{
		".env":              validValidateEnv,
		"config/roles.json": "{ this is not json",
	})
	cmd := &ConfigValidateCmd{To: root, Format: "text"}
	if err := cmd.Run(); err == nil {
		t.Fatal("malformed roles.json must fail validate")
	}
}

// A well-formed JSON body with a wrong value type passes a map[string]any
// probe but kills the server's LoadRoles at boot, so validate must catch
// it by mirroring the server's role shape.
func TestConfigValidateFailsOnWrongRoleType(t *testing.T) {
	withCleanEnv(t)
	root := t.TempDir()
	writeTree(t, root, map[string]string{
		".env":              validValidateEnv,
		"config/roles.json": `{"admin": {"identities": [], "can_message_unlimited": "yes"}}` + "\n",
	})
	cmd := &ConfigValidateCmd{To: root, Format: "text"}
	if err := cmd.Run(); err == nil {
		t.Fatal("wrong role value type must fail validate")
	}
}

func TestConfigValidateFailsOnMissingEnv(t *testing.T) {
	withCleanEnv(t)
	root := t.TempDir()
	writeTree(t, root, map[string]string{
		"config/roles.json": "{}\n",
	})
	cmd := &ConfigValidateCmd{To: root, Format: "text"}
	if err := cmd.Run(); err == nil {
		t.Fatal("missing .env must fail validate")
	}
}
